import { generateId } from '../utils/ids'
import { getDefaultWeights } from '../components/scorecard/criteria'

// Pre-generate area IDs so scorecard scores can reference them
const _areaIds = Array.from({ length: 13 }, () => generateId())

export const defaultSettings = {
  theme: 'dark',
  ollamaUrl: 'http://localhost:11434',
  ollamaModel: 'llama3.2',
  homeValue: 400000,
  homePurchasePrice: 500000,
  mortgageBalance: 0,
  budgetMin: 750000,
  budgetMax: 1250000,
  targetYear: 2030,
  acreageMin: 5,
  acreageMax: 20,
}

export const defaultFinances = {
  savings: 0,
  monthlyContribution: 0,
  categories: [
    { id: generateId(), name: 'Land Purchase', estimate: 200000, allocated: 0, spent: 0 },
    { id: generateId(), name: 'Architect & Design', estimate: 60000, allocated: 0, spent: 0 },
    { id: generateId(), name: 'Permits & Fees', estimate: 15000, allocated: 0, spent: 0 },
    { id: generateId(), name: 'Site Work', estimate: 80000, allocated: 0, spent: 0 },
    { id: generateId(), name: 'Construction', estimate: 500000, allocated: 0, spent: 0 },
    { id: generateId(), name: 'Infrastructure', estimate: 50000, allocated: 0, spent: 0 },
    { id: generateId(), name: 'Interior & Finishes', estimate: 100000, allocated: 0, spent: 0 },
    { id: generateId(), name: 'Landscaping', estimate: 40000, allocated: 0, spent: 0 },
    { id: generateId(), name: 'Contingency', estimate: 155000, allocated: 0, spent: 0 },
  ],
}

export const defaultRequirements = [
  {
    id: generateId(),
    item: '10-Gig networking throughout',
    category: 'Infrastructure',
    priority: 'must-have',
    notes: 'Cat6a minimum, fiber backbone preferred',
    done: false,
    estimatedCost: 15000,
    addedBy: 'system',
    createdAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    item: 'Dedicated network rack / server room',
    category: 'Infrastructure',
    priority: 'must-have',
    notes: 'Climate-controlled closet with UPS',
    done: false,
    estimatedCost: 8000,
    addedBy: 'system',
    createdAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    item: 'Home theater room',
    category: 'Interior',
    priority: 'must-have',
    notes: 'Dedicated room with sound isolation',
    done: false,
    estimatedCost: 35000,
    addedBy: 'system',
    createdAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    item: 'Detached shop / workshop',
    category: 'Exterior',
    priority: 'must-have',
    notes: 'Minimum 30x40, insulated, with power',
    done: false,
    estimatedCost: 50000,
    addedBy: 'system',
    createdAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    item: '5-20 acres of land',
    category: 'Land',
    priority: 'must-have',
    notes: 'Rural area, 1-2 hours from Houston',
    done: false,
    estimatedCost: 200000,
    addedBy: 'system',
    createdAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    item: 'Dedicated home office',
    category: 'Interior',
    priority: 'must-have',
    notes: 'Separate from living areas, good natural light',
    done: false,
    estimatedCost: 10000,
    addedBy: 'system',
    createdAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    item: 'Solar-ready wiring',
    category: 'Infrastructure',
    priority: 'nice-to-have',
    notes: 'Pre-wire for future solar panel installation',
    done: false,
    estimatedCost: 5000,
    addedBy: 'system',
    createdAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    item: 'Open concept kitchen',
    category: 'Interior',
    priority: 'nice-to-have',
    notes: 'Kitchen flows into living/dining area',
    done: false,
    estimatedCost: 0,
    addedBy: 'system',
    createdAt: new Date().toISOString(),
  },
]

export const defaultTimeline = [
  // Phase 1: Research & Planning (Jun 2025 – Dec 2025)
  { id: generateId(), milestone: 'Define requirements & wishlist', phase: 'Research & Planning', targetDate: '2025-06-30', status: 'not-started', notes: '', completedDate: null },
  { id: generateId(), milestone: 'Research locations & land options', phase: 'Research & Planning', targetDate: '2025-09-30', status: 'not-started', notes: '', completedDate: null },
  { id: generateId(), milestone: 'Finalize budget & financing plan', phase: 'Research & Planning', targetDate: '2025-12-31', status: 'not-started', notes: '', completedDate: null },

  // Phase 2: Land Acquisition (Jan 2026 – Jun 2026)
  { id: generateId(), milestone: 'Select and purchase land', phase: 'Land Acquisition', targetDate: '2026-03-31', status: 'not-started', notes: '', completedDate: null },
  { id: generateId(), milestone: 'Survey & soil testing', phase: 'Land Acquisition', targetDate: '2026-06-30', status: 'not-started', notes: '', completedDate: null },

  // Phase 3: Design & Permits (Jul 2026 – Mar 2027)
  { id: generateId(), milestone: 'Hire architect', phase: 'Design & Permits', targetDate: '2026-08-31', status: 'not-started', notes: '', completedDate: null },
  { id: generateId(), milestone: 'Complete house plans', phase: 'Design & Permits', targetDate: '2027-01-31', status: 'not-started', notes: '', completedDate: null },
  { id: generateId(), milestone: 'Obtain building permits', phase: 'Design & Permits', targetDate: '2027-03-31', status: 'not-started', notes: '', completedDate: null },

  // Phase 4: Site Preparation (Apr 2027 – Jun 2027)
  { id: generateId(), milestone: 'Clear & grade site', phase: 'Site Preparation', targetDate: '2027-05-31', status: 'not-started', notes: '', completedDate: null },

  // Phase 5: Construction (Jul 2027 – Mar 2029)
  { id: generateId(), milestone: 'Foundation & framing', phase: 'Construction', targetDate: '2027-12-31', status: 'not-started', notes: '', completedDate: null },
  { id: generateId(), milestone: 'Systems rough-in (electrical, plumbing, HVAC)', phase: 'Construction', targetDate: '2028-06-30', status: 'not-started', notes: '', completedDate: null },
  { id: generateId(), milestone: 'Interior finishes & landscaping', phase: 'Construction', targetDate: '2029-03-31', status: 'not-started', notes: '', completedDate: null },

  // Phase 6: Move In (Apr 2029 – Jun 2029)
  { id: generateId(), milestone: 'Final inspection & move in', phase: 'Move In', targetDate: '2029-06-30', status: 'not-started', notes: '', completedDate: null },
]

// Two-tier location model: Areas contain Properties
export const defaultAreas = [
  // ═══════════════════════════════════════════════
  // PACIFIC NORTHWEST
  // ═══════════════════════════════════════════════
  {
    id: _areaIds[0],
    name: 'Battle Ground / Ridgefield Area',
    state: 'Washington',
    county: 'Clark County',
    metroArea: 'Portland, OR',
    distanceToMetro: '30 min / 20 miles',
    tags: ['pnw', 'no income tax', 'near portland', 'growing'],
    coordinates: { lat: 45.78, lng: -122.53 },
    climate: {
      avgHighSummer: '82°F',
      avgLowWinter: '34°F',
      annualRainfall: '44 inches',
      hardiness: '8b',
    },
    infrastructure: {
      internetProviders: 'Xfinity, CenturyLink, Starlink',
      waterSource: 'Well water (rural), Clark PUD (subdivisions)',
      electricProvider: 'Clark PUD',
      cellCoverage: 'AT&T good, T-Mobile good, Verizon good',
    },
    landInfo: {
      avgPricePerAcre: 45000,
      typicalLotSize: '5-20 acres',
      terrain: 'Rolling hills, mixed timber',
      soilType: 'Volcanic silt loam',
      floodRisk: 'Low (upland areas)',
    },
    taxInfo: {
      propertyTaxRate: '0.88%',
      homesteadExemption: 'Senior/disabled exemption available',
    },
    schoolDistrict: 'Battle Ground SD, Ridgefield SD (top-rated)',
    nearestHospital: 'PeaceHealth SW Medical (Vancouver, 25 min); OHSU (Portland, 40 min) — MG specialty',
    nearestGrocery: 'Fred Meyer, Safeway (Battle Ground, 10 min)',
    population: '~23,000 (Battle Ground)',
    pros: ['No state income tax', 'Near PDX airport (35 min)', 'OHSU neurology 40 min', 'Great schools', 'Mild 4-season climate'],
    cons: ['WA sales tax 8.6%', 'Rain Oct-May', 'Land prices rising fast', 'Permitting moderate (county review)'],
    notes: 'WA has no income tax — huge advantage. Live in WA, shop in OR (no sales tax). OHSU is a top MG treatment center, only 40 min away. PDX international airport ~35 min. Ridgefield SD is one of the fastest-growing and highest-rated in the state. Owner-builder allowed in WA but must pull permits through county. Clark County requires inspections but process is straightforward.',
    rating: 4,
    createdAt: new Date().toISOString(),
  },
  {
    id: _areaIds[1],
    name: 'Olympia / Yelm / Tenino Area',
    state: 'Washington',
    county: 'Thurston County',
    metroArea: 'Seattle-Tacoma',
    distanceToMetro: '60 min / 60 miles to Tacoma',
    tags: ['pnw', 'no income tax', 'rural', 'affordable', 'state capital'],
    coordinates: { lat: 46.97, lng: -122.90 },
    climate: {
      avgHighSummer: '78°F',
      avgLowWinter: '33°F',
      annualRainfall: '50 inches',
      hardiness: '8b',
    },
    infrastructure: {
      internetProviders: 'Xfinity (Olympia), CenturyLink, Starlink (rural)',
      waterSource: 'Well water (Yelm/Tenino), city water (Olympia)',
      electricProvider: 'Puget Sound Energy, Thurston PUD',
      cellCoverage: 'AT&T fair-good, T-Mobile good, Verizon fair',
    },
    landInfo: {
      avgPricePerAcre: 25000,
      typicalLotSize: '5-20 acres',
      terrain: 'Prairie, light timber, rolling',
      soilType: 'Glacial till, sandy loam',
      floodRisk: 'Low-Moderate (check Nisqually floodplain)',
    },
    taxInfo: {
      propertyTaxRate: '1.02%',
      homesteadExemption: 'Senior/disabled exemption available',
    },
    schoolDistrict: 'Yelm Community Schools, Olympia SD, Tumwater SD',
    nearestHospital: 'Providence St. Peter (Olympia, 20 min); UW Medicine/Madigan (Tacoma, 50 min) — MG specialty',
    nearestGrocery: 'Safeway, Walmart (Yelm/Olympia, 10-15 min)',
    population: '~55,000 (Olympia metro)',
    pros: ['No state income tax', 'Cheaper land than Clark Co', 'Near SeaTac (75 min)', 'State capital amenities', 'Rural feel near Yelm/Tenino'],
    cons: ['SeaTac is 75 min (borderline)', 'Very rainy', 'MG care requires Tacoma/Seattle trip', 'Rural internet spotty'],
    notes: 'Yelm and Tenino areas offer much cheaper land than closer-to-Portland options. No income tax. SeaTac airport is ~75 min which is borderline on the 90-min requirement. UW Medicine in Seattle has excellent MG treatment but is 90+ min. Madigan Army Medical Center in Tacoma is closer (50 min) but requires military affiliation. Thurston County permitting is moderate — owner-builder allowed. Very rainy climate.',
    rating: 3,
    createdAt: new Date().toISOString(),
  },
  {
    id: _areaIds[2],
    name: 'Woodland / Castle Rock / Kalama Area',
    state: 'Washington',
    county: 'Cowlitz County',
    metroArea: 'Portland, OR',
    distanceToMetro: '45 min / 35 miles',
    tags: ['pnw', 'no income tax', 'rural', 'cheap land', 'i-5 corridor'],
    coordinates: { lat: 46.15, lng: -122.77 },
    climate: {
      avgHighSummer: '80°F',
      avgLowWinter: '33°F',
      annualRainfall: '48 inches',
      hardiness: '8b',
    },
    infrastructure: {
      internetProviders: 'CenturyLink, Starlink, local wireless ISPs',
      waterSource: 'Well water (rural)',
      electricProvider: 'Cowlitz PUD (very cheap rates)',
      cellCoverage: 'AT&T fair, T-Mobile fair, Verizon fair (gaps in hills)',
    },
    landInfo: {
      avgPricePerAcre: 15000,
      typicalLotSize: '5-40 acres',
      terrain: 'Foothills, timber, river valleys',
      soilType: 'Volcanic alluvial, silty',
      floodRisk: 'Moderate (check Cowlitz/Columbia floodplain)',
    },
    taxInfo: {
      propertyTaxRate: '0.95%',
      homesteadExemption: 'Senior/disabled exemption available',
    },
    schoolDistrict: 'Woodland SD, Castle Rock SD, Kalama SD (small, decent)',
    nearestHospital: 'PeaceHealth St. John (Longview, 20 min); OHSU (Portland, 55 min) — MG specialty',
    nearestGrocery: 'Safeway, Walmart (Woodland/Longview, 10-15 min)',
    population: '~6,000 (Woodland)',
    pros: ['No state income tax', 'Very cheap land', 'Cheap electricity (Cowlitz PUD)', 'PDX airport 50 min', 'OHSU 55 min for MG'],
    cons: ['Very rural/small town', 'Limited internet options', 'Rain', 'Smaller school districts', 'Cell coverage gaps'],
    notes: 'Cowlitz County is the budget PNW option. Land is significantly cheaper than Clark County. Cowlitz PUD has some of the cheapest electricity in the nation. Still within striking distance of PDX airport (~50 min) and OHSU for MG treatment (~55 min). Trade-off is smaller communities and limited infrastructure. Owner-builder friendly. Cowlitz County permitting is relatively relaxed for rural parcels.',
    rating: 3,
    createdAt: new Date().toISOString(),
  },

  // ═══════════════════════════════════════════════
  // SOUTHWEST
  // ═══════════════════════════════════════════════
  {
    id: _areaIds[3],
    name: 'Prescott Valley / Chino Valley Area',
    state: 'Arizona',
    county: 'Yavapai County',
    metroArea: 'Phoenix',
    distanceToMetro: '90 min / 100 miles',
    tags: ['southwest', 'low taxes', 'owner-builder', '4 seasons', 'high desert'],
    coordinates: { lat: 34.61, lng: -112.32 },
    climate: {
      avgHighSummer: '93°F',
      avgLowWinter: '23°F',
      annualRainfall: '13 inches',
      hardiness: '7b',
    },
    infrastructure: {
      internetProviders: 'Suddenlink, CenturyLink, Starlink',
      waterSource: 'Well water, some municipal (Prescott Valley)',
      electricProvider: 'Arizona Public Service (APS)',
      cellCoverage: 'AT&T good, T-Mobile good, Verizon good',
    },
    landInfo: {
      avgPricePerAcre: 12000,
      typicalLotSize: '2-40 acres',
      terrain: 'High desert, rolling grassland, juniper/pinon',
      soilType: 'Rocky decomposed granite, clay',
      floodRisk: 'Low (flash flood washes — check specific parcels)',
    },
    taxInfo: {
      propertyTaxRate: '0.58%',
      homesteadExemption: 'Primary residence assessed at lower ratio',
    },
    schoolDistrict: 'Humboldt USD, Prescott USD, Chino Valley USD',
    nearestHospital: 'Yavapai Regional Medical (Prescott, 15 min); Banner/Mayo Clinic (Phoenix, 90 min) — MG specialty',
    nearestGrocery: 'Fry\'s, Safeway, Walmart (Prescott Valley, 10 min)',
    population: '~48,000 (Prescott Valley)',
    pros: ['Very low property tax (0.58%)', 'AZ is owner-builder state', 'Cheap land', '4-season high desert climate', 'Low humidity', 'No state income tax on first $27K (single)'],
    cons: ['AZ has 2.5% flat income tax', '90 min to PHX airport (borderline)', 'Water scarcity concerns', 'MG care requires Phoenix trip', 'Fire risk in summer'],
    notes: 'Arizona is one of the best owner-builder states — you can act as your own GC and self-certify much of the work in unincorporated Yavapai County. Property tax is incredibly low (0.58%). High desert climate means 4 real seasons without Houston-level heat. Land is very affordable. PHX Sky Harbor (major international) is right at the 90-min mark. Mayo Clinic Scottsdale has excellent MG treatment but is also ~90 min. AZ flat 2.5% income tax is low. Water rights and availability are the main concern — verify well drilling feasibility on any parcel.',
    rating: 4,
    createdAt: new Date().toISOString(),
  },
  {
    id: _areaIds[4],
    name: 'Vail / Marana / Tucson Outskirts',
    state: 'Arizona',
    county: 'Pima County',
    metroArea: 'Tucson',
    distanceToMetro: '20-30 min / 15-25 miles',
    tags: ['southwest', 'low taxes', 'owner-builder', 'university town', 'hot summers'],
    coordinates: { lat: 32.05, lng: -110.70 },
    climate: {
      avgHighSummer: '100°F',
      avgLowWinter: '38°F',
      annualRainfall: '12 inches',
      hardiness: '9a',
    },
    infrastructure: {
      internetProviders: 'Cox, CenturyLink, Starlink',
      waterSource: 'Tucson Water (Marana), well water (rural Vail)',
      electricProvider: 'Tucson Electric Power (TEP)',
      cellCoverage: 'AT&T good, T-Mobile good, Verizon good',
    },
    landInfo: {
      avgPricePerAcre: 8000,
      typicalLotSize: '5-40 acres',
      terrain: 'Sonoran desert, saguaro, mesquite',
      soilType: 'Sandy, caliche, decomposed granite',
      floodRisk: 'Low-Moderate (arroyos/washes)',
    },
    taxInfo: {
      propertyTaxRate: '0.71%',
      homesteadExemption: 'Primary residence assessed at lower ratio',
    },
    schoolDistrict: 'Vail USD (excellent — top-rated in AZ), Marana USD (good)',
    nearestHospital: 'Banner University Medical Center (Tucson, 25 min) — neurology dept, UA neuromuscular clinic',
    nearestGrocery: 'Fry\'s, Safeway, Costco (15-20 min)',
    population: '~15,000 (Vail), ~50,000 (Marana)',
    pros: ['Very cheap land', 'Vail USD is top AZ school district', 'Owner-builder state', 'UA Medical for MG care (25 min)', 'Low property tax', 'Tucson airport + 90 min to PHX'],
    cons: ['Hot summers (100°F+)', 'Desert landscape — not green', 'Water scarcity concerns', '2.5% state income tax', 'Tucson airport is small (TUS)'],
    notes: 'Vail is the hidden gem — Vail USD is consistently the top-rated school district in Arizona. Land prices are very low east and south of Tucson. Banner University Medical Center has a neuromuscular clinic affiliated with University of Arizona. PHX is ~90 min for major international flights. TUS (Tucson International) has some direct flights but is smaller. AZ owner-builder friendly. Summers are hot (100°F+) but dry heat. Great for someone who wants cheap land with good schools in a university town setting.',
    rating: 3,
    createdAt: new Date().toISOString(),
  },
  {
    id: _areaIds[5],
    name: 'Casa Grande / Florence / Coolidge Area',
    state: 'Arizona',
    county: 'Pinal County',
    metroArea: 'Phoenix',
    distanceToMetro: '50 min / 55 miles to Phoenix',
    tags: ['southwest', 'low taxes', 'owner-builder', 'cheap land', 'between phx and tucson'],
    coordinates: { lat: 32.88, lng: -111.75 },
    climate: {
      avgHighSummer: '106°F',
      avgLowWinter: '36°F',
      annualRainfall: '9 inches',
      hardiness: '9b',
    },
    infrastructure: {
      internetProviders: 'CenturyLink, Starlink, some Cox (Casa Grande)',
      waterSource: 'Well water (rural), Casa Grande city water',
      electricProvider: 'Arizona Public Service (APS), Electrical District',
      cellCoverage: 'AT&T fair-good, T-Mobile fair, Verizon fair',
    },
    landInfo: {
      avgPricePerAcre: 5000,
      typicalLotSize: '5-40 acres',
      terrain: 'Flat desert, former agricultural',
      soilType: 'Sandy, alluvial, alkaline',
      floodRisk: 'Low (very flat, check washes)',
    },
    taxInfo: {
      propertyTaxRate: '0.62%',
      homesteadExemption: 'Primary residence assessed at lower ratio',
    },
    schoolDistrict: 'Casa Grande USD, Florence USD, Coolidge USD (average)',
    nearestHospital: 'Banner Casa Grande Medical (15 min); Banner/Mayo (Phoenix, 50 min) — MG specialty',
    nearestGrocery: 'Fry\'s, Walmart (Casa Grande, 10-15 min)',
    population: '~58,000 (Casa Grande)',
    pros: ['Cheapest land in the list', 'PHX airport 55 min', 'Very low property tax', 'Owner-builder state', 'Near I-10 and I-8'],
    cons: ['Extremely hot summers (106°F)', 'Flat desert — not scenic', 'Schools are average', 'Water table concerns', 'Limited nightlife/culture'],
    notes: 'The budget pick. Pinal County between Phoenix and Tucson has some of the cheapest land in the West. PHX Sky Harbor is under 60 min for international flights. Banner/Mayo in Phoenix for MG care is ~50 min. Trade-off: it\'s flat, hot desert with average schools. But if budget is the priority and you want maximum acreage for minimum cost in an owner-builder state, this is hard to beat. Growing area — TSMC fab plant being built nearby bringing jobs and infrastructure.',
    rating: 3,
    createdAt: new Date().toISOString(),
  },

  // ═══════════════════════════════════════════════
  // TEXAS
  // ═══════════════════════════════════════════════
  {
    id: _areaIds[6],
    name: 'Dripping Springs / Wimberley Area',
    state: 'Texas',
    county: 'Hays County',
    metroArea: 'Austin',
    distanceToMetro: '30 min / 25 miles',
    tags: ['texas', 'no income tax', 'hill country', 'austin metro', 'good schools'],
    coordinates: { lat: 30.19, lng: -98.09 },
    climate: {
      avgHighSummer: '96°F',
      avgLowWinter: '36°F',
      annualRainfall: '34 inches',
      hardiness: '8b',
    },
    infrastructure: {
      internetProviders: 'Spectrum, GVTC Fiber, Starlink',
      waterSource: 'Well water, some Hays Co water supply (WSC)',
      electricProvider: 'Pedernales Electric Co-op',
      cellCoverage: 'AT&T good, T-Mobile good, Verizon good',
    },
    landInfo: {
      avgPricePerAcre: 40000,
      typicalLotSize: '5-20 acres',
      terrain: 'Hill Country — rolling limestone hills, oak groves, creeks',
      soilType: 'Limestone, rocky, thin topsoil',
      floodRisk: 'Moderate (flash floods in creek areas — check FEMA maps)',
    },
    taxInfo: {
      propertyTaxRate: '1.82%',
      homesteadExemption: '$100K homestead + 20% of appraised value',
    },
    schoolDistrict: 'Dripping Springs ISD (excellent — top 5% in TX)',
    nearestHospital: 'Ascension Seton (Austin, 35 min); Dell Seton Medical / UT Health (Austin, 40 min) — MG specialty',
    nearestGrocery: 'HEB (Dripping Springs, 10 min)',
    population: '~6,000 (Dripping Springs)',
    pros: ['No state income tax', 'Dripping Springs ISD is elite', 'AUS airport 40 min', 'Hill Country beauty', 'Austin culture access', 'GVTC fiber internet available'],
    cons: ['High property tax (1.82%)', 'Land prices rising fast', 'Hot summers', 'Flash flood risk in valleys', 'TX permitting varies by jurisdiction'],
    notes: 'Hill Country gem near Austin. Dripping Springs ISD is one of the top school districts in Texas. No state income tax but property taxes are high (offset by generous homestead exemption). AUS airport is ~40 min (international flights expanding). UT Health Austin has neurology for MG care. GVTC offers true fiber internet in some areas — verify coverage for specific parcels. Land has gotten expensive near Dripping Springs proper but cheaper further toward Wimberley and Johnson City. TX permitting: unincorporated Hays County is fairly relaxed, but Dripping Springs city limits have more regulation.',
    rating: 4,
    createdAt: new Date().toISOString(),
  },
  {
    id: _areaIds[7],
    name: 'Canyon Lake / New Braunfels Area',
    state: 'Texas',
    county: 'Comal County',
    metroArea: 'San Antonio',
    distanceToMetro: '30 min / 30 miles to San Antonio',
    tags: ['texas', 'no income tax', 'hill country', 'lake', 'between austin and sa'],
    coordinates: { lat: 29.87, lng: -98.25 },
    climate: {
      avgHighSummer: '95°F',
      avgLowWinter: '37°F',
      annualRainfall: '35 inches',
      hardiness: '8b',
    },
    infrastructure: {
      internetProviders: 'Spectrum, GVEC Fiber, Starlink',
      waterSource: 'Well water (Canyon Lake), New Braunfels Utilities',
      electricProvider: 'GVEC (Guadalupe Valley Electric Co-op)',
      cellCoverage: 'AT&T good, T-Mobile good, Verizon good',
    },
    landInfo: {
      avgPricePerAcre: 30000,
      typicalLotSize: '5-20 acres',
      terrain: 'Hill Country — cedar/oak hills, canyons, lake views',
      soilType: 'Limestone, rocky, clay pockets',
      floodRisk: 'Moderate (Guadalupe River/Comal River corridor)',
    },
    taxInfo: {
      propertyTaxRate: '1.67%',
      homesteadExemption: '$100K homestead + 20% of appraised value',
    },
    schoolDistrict: 'Comal ISD (excellent — top 10% in TX)',
    nearestHospital: 'Christus Santa Rosa (New Braunfels, 15 min); UT Health SA / Brooke Army Med (SA, 40 min) — MG specialty',
    nearestGrocery: 'HEB (New Braunfels, 15 min)',
    population: '~22,000 (Canyon Lake area)',
    pros: ['No state income tax', 'Comal ISD excellent', 'SAT airport 40 min + AUS 50 min', 'Lake lifestyle', 'German heritage/culture', 'GVEC fiber expanding'],
    cons: ['High property tax', 'Tourist traffic (summer)', 'Flash flood risk', 'Hot summers', 'Land near lake is premium'],
    notes: 'Between Austin and San Antonio with access to both metros. Canyon Lake area offers Hill Country living with lake recreation. Comal ISD is one of the best in Texas. SAT airport (international) is 40 min, AUS is 50 min — double coverage. UT Health San Antonio has neuromuscular care for MG. GVEC is rolling out fiber broadband to rural areas. Unincorporated Comal County is relatively relaxed on permitting. New Braunfels has excellent amenities (HEB, restaurants, Schlitterbahn). Land away from the lake is more affordable.',
    rating: 4,
    createdAt: new Date().toISOString(),
  },
  {
    id: _areaIds[8],
    name: 'Bastrop / Smithville Area',
    state: 'Texas',
    county: 'Bastrop County',
    metroArea: 'Austin',
    distanceToMetro: '35 min / 30 miles',
    tags: ['texas', 'no income tax', 'lost pines', 'affordable', 'rural'],
    coordinates: { lat: 30.11, lng: -97.31 },
    climate: {
      avgHighSummer: '97°F',
      avgLowWinter: '37°F',
      annualRainfall: '37 inches',
      hardiness: '8b/9a',
    },
    infrastructure: {
      internetProviders: 'Spectrum (Bastrop), Starlink (rural), local fiber expanding',
      waterSource: 'Well water (rural), Aqua Water Supply',
      electricProvider: 'Bluebonnet Electric Co-op',
      cellCoverage: 'AT&T good, T-Mobile fair-good, Verizon fair',
    },
    landInfo: {
      avgPricePerAcre: 20000,
      typicalLotSize: '5-30 acres',
      terrain: 'Lost Pines — loblolly pine forest, post-oak savanna, rolling',
      soilType: 'Sandy loam, some clay',
      floodRisk: 'Low-Moderate (Colorado River corridor)',
    },
    taxInfo: {
      propertyTaxRate: '1.89%',
      homesteadExemption: '$100K homestead + 20% of appraised value',
    },
    schoolDistrict: 'Bastrop ISD, Smithville ISD (average to good)',
    nearestHospital: 'Ascension Seton Bastrop (10 min); Dell Seton Medical (Austin, 40 min) — MG specialty',
    nearestGrocery: 'HEB (Bastrop, 10 min)',
    population: '~10,000 (Bastrop)',
    pros: ['No state income tax', 'Cheapest TX Hill Country-adjacent land', 'AUS airport 30-40 min', 'Beautiful Lost Pines scenery', 'Austin access', 'Relaxed unincorporated permitting'],
    cons: ['High property tax', 'Wildfire risk (2011 fires)', 'Schools are average', 'Summer heat', 'Rural internet in spots'],
    notes: 'The budget Austin-area option. Bastrop County has significantly cheaper land than Hays or Comal Counties while still being 35 min from Austin. The Lost Pines ecosystem is uniquely beautiful — loblolly pines that are an ecological island separated from East Texas pine forests. AUS airport is 30-40 min. Dell Seton in Austin for MG care is ~40 min. Unincorporated Bastrop County has very relaxed permitting. Bluebonnet Electric is reliable. Main concern is wildfire risk (2011 Complex Fire devastated the area) — consider defensible space in site planning. Smithville is a charming small town.',
    rating: 3,
    createdAt: new Date().toISOString(),
  },

  // ═══════════════════════════════════════════════
  // CENTRAL / MIDWEST
  // ═══════════════════════════════════════════════
  {
    id: _areaIds[9],
    name: 'Colorado Springs / Falcon / Peyton Area',
    state: 'Colorado',
    county: 'El Paso County',
    metroArea: 'Denver / Colorado Springs',
    distanceToMetro: '15 min to COS / 70 min to Denver',
    tags: ['midwest', '4 seasons', 'military town', '300 days sunshine', 'mountain views'],
    coordinates: { lat: 38.88, lng: -104.70 },
    climate: {
      avgHighSummer: '86°F',
      avgLowWinter: '18°F',
      annualRainfall: '17 inches',
      hardiness: '6a',
    },
    infrastructure: {
      internetProviders: 'Comcast Xfinity, CenturyLink, Starlink (Falcon/Peyton)',
      waterSource: 'Well water (Falcon/Peyton), Colorado Springs Utilities',
      electricProvider: 'Mountain View Electric (Falcon/Peyton), CS Utilities',
      cellCoverage: 'AT&T good, T-Mobile good, Verizon good',
    },
    landInfo: {
      avgPricePerAcre: 18000,
      typicalLotSize: '5-35 acres',
      terrain: 'High plains, mesa, Pikes Peak views',
      soilType: 'Clay, sandy loam, rocky',
      floodRisk: 'Low (high and dry)',
    },
    taxInfo: {
      propertyTaxRate: '0.52%',
      homesteadExemption: 'CO Senior Homestead Exemption (65+)',
    },
    schoolDistrict: 'Academy D20 (excellent), Falcon D49 (good, growing)',
    nearestHospital: 'UCHealth Memorial (COS, 20 min); UCHealth University of Colorado (Denver, 75 min) — MG specialty',
    nearestGrocery: 'King Soopers, Safeway, Walmart (15-20 min)',
    population: '~490,000 (Colorado Springs)',
    pros: ['Very low property tax (0.52%)', '300 days sunshine', 'DEN airport 75 min', 'Mountain views', 'Academy D20 schools', '4.4% flat income tax', 'Not humid'],
    cons: ['CO 4.4% income tax', 'Cold winters (18°F lows)', 'Dry — no water features', 'Wind on eastern plains', 'Hail season (spring)'],
    notes: 'Colorado Springs area (especially Falcon and Peyton to the east) offers affordable acreage with Pikes Peak views. El Paso County has the lowest property tax rate in this entire list at 0.52%. DEN (major international) is ~75 min via I-25. UCHealth in Denver has a neuromuscular center for MG care (~75 min). Academy D20 is one of the top school districts in Colorado. 300 days of sunshine — even winters are sunny despite cold. CO has a 4.4% flat income tax which is moderate. Owner-builder is allowed in El Paso County with permits. Falcon/Peyton are growing but still have large rural parcels available.',
    rating: 4,
    createdAt: new Date().toISOString(),
  },
  {
    id: _areaIds[10],
    name: 'Valparaiso / Chesterton Area',
    state: 'Indiana',
    county: 'Porter County',
    metroArea: 'Chicago',
    distanceToMetro: '60 min / 55 miles to Chicago Loop',
    tags: ['midwest', 'low taxes', 'near chicago', 'affordable', 'dunes'],
    coordinates: { lat: 41.47, lng: -87.06 },
    climate: {
      avgHighSummer: '84°F',
      avgLowWinter: '17°F',
      annualRainfall: '38 inches',
      hardiness: '6a',
    },
    infrastructure: {
      internetProviders: 'Comcast Xfinity, Frontier, Starlink',
      waterSource: 'Indiana American Water (Valpo), well water (rural)',
      electricProvider: 'NIPSCO (Northern Indiana)',
      cellCoverage: 'AT&T good, T-Mobile good, Verizon good',
    },
    landInfo: {
      avgPricePerAcre: 15000,
      typicalLotSize: '5-20 acres',
      terrain: 'Flat to gently rolling, prairie remnants, some woodland',
      soilType: 'Rich glacial loam, black soil',
      floodRisk: 'Low (well-drained)',
    },
    taxInfo: {
      propertyTaxRate: '0.85%',
      homesteadExemption: '$48,000 standard deduction + mortgage deduction',
    },
    schoolDistrict: 'Valparaiso Community Schools (excellent), Duneland (Chesterton, excellent)',
    nearestHospital: 'Northwest Health Porter (Valpo, 10 min); Northwestern Medicine/Rush (Chicago, 75 min) — MG specialty',
    nearestGrocery: 'Strack & Van Til, Walmart, Aldi (Valpo, 10 min)',
    population: '~34,000 (Valparaiso)',
    pros: ['Very low 3.05% flat income tax', 'Low property tax', 'ORD/MDW airports 60-75 min', 'Chicago medical access for MG', 'Great schools', 'Cheap land', 'Indiana Dunes nearby'],
    cons: ['Cold winters', 'Lake effect snow', 'Flat terrain', 'Not as scenic', 'Indiana can feel isolated culturally'],
    notes: 'The Midwest value pick. Indiana has one of the lowest flat income tax rates in the nation at 3.05%. Property tax is low with generous homestead deductions. Porter County gives you access to Chicago (ORD/MDW international airports, 60-75 min) and world-class MG treatment at Northwestern Medicine or Rush (75 min). Both Valparaiso and Duneland school districts are excellent. Land is very affordable. Trade-off: cold winters with lake effect snow, flat terrain. But culturally you have Chicago access for dining, entertainment, and sports. South Shore Line commuter rail to Chicago from nearby.',
    rating: 4,
    createdAt: new Date().toISOString(),
  },

  // ═══════════════════════════════════════════════
  // NORTHEAST
  // ═══════════════════════════════════════════════
  {
    id: _areaIds[11],
    name: 'Milford / Amherst / Hollis Area',
    state: 'New Hampshire',
    county: 'Hillsborough County',
    metroArea: 'Boston / Manchester',
    distanceToMetro: '50 min to Boston / 25 min to Manchester',
    tags: ['northeast', 'no income tax', 'no sales tax', 'new england charm', 'good schools'],
    coordinates: { lat: 42.84, lng: -71.65 },
    climate: {
      avgHighSummer: '82°F',
      avgLowWinter: '14°F',
      annualRainfall: '44 inches',
      hardiness: '5b',
    },
    infrastructure: {
      internetProviders: 'Comcast Xfinity, Consolidated Communications, Starlink',
      waterSource: 'Well water (most rural areas), some town water',
      electricProvider: 'Eversource, Liberty Utilities',
      cellCoverage: 'AT&T good, T-Mobile good, Verizon good',
    },
    landInfo: {
      avgPricePerAcre: 35000,
      typicalLotSize: '5-15 acres',
      terrain: 'Wooded hills, stone walls, streams',
      soilType: 'Rocky glacial till, sandy loam pockets',
      floodRisk: 'Low (upland areas)',
    },
    taxInfo: {
      propertyTaxRate: '2.09%',
      homesteadExemption: 'Town-dependent, varies ($15K-$50K)',
    },
    schoolDistrict: 'Hollis-Brookline SAU (excellent), Amherst/Souhegan (excellent)',
    nearestHospital: 'St. Joseph Hospital (Nashua, 20 min); Mass General (Boston, 75 min) — top MG center in nation',
    nearestGrocery: 'Market Basket, Shaw\'s, Hannaford (10-15 min)',
    population: '~15,000 (Milford)',
    pros: ['No state income tax', 'No sales tax', 'Mass General MG care 75 min', 'BOS airport 60 min', 'Excellent schools', 'NJ friends can drive (3-4 hrs)', 'New England beauty'],
    cons: ['High property tax (2.09%)', 'Cold winters', 'Land more expensive than South/West', 'Snow/ice Nov-Mar', 'Higher grocery/goods costs'],
    notes: 'The New England pick. NH has NO income tax AND no sales tax — one of only a few states with both. Trade-off is high property taxes (NH funds schools through property tax instead). Mass General Hospital in Boston is arguably the #1 MG treatment center in the country — 75 min away. BOS Logan International is ~60 min. Hollis-Brookline and Souhegan school districts are among the best in NH (and therefore the country). NJ friends can drive up in 3-4 hours. Beautiful New England character — stone walls, covered bridges, fall foliage. Town-level permitting varies, but many NH towns are fairly owner-builder friendly, especially for rural parcels.',
    rating: 4,
    createdAt: new Date().toISOString(),
  },
  {
    id: _areaIds[12],
    name: 'Sturbridge / Brookfield / Spencer Area',
    state: 'Massachusetts',
    county: 'Worcester County',
    metroArea: 'Boston / Worcester',
    distanceToMetro: '60 min to Boston / 25 min to Worcester',
    tags: ['northeast', 'new england', 'rural ma', 'mass general access', 'cultural'],
    coordinates: { lat: 42.10, lng: -72.08 },
    climate: {
      avgHighSummer: '82°F',
      avgLowWinter: '14°F',
      annualRainfall: '46 inches',
      hardiness: '6a',
    },
    infrastructure: {
      internetProviders: 'Spectrum, Verizon Fios (some areas), Starlink',
      waterSource: 'Well water (rural), some town water',
      electricProvider: 'National Grid',
      cellCoverage: 'AT&T good, T-Mobile fair-good, Verizon good',
    },
    landInfo: {
      avgPricePerAcre: 25000,
      typicalLotSize: '5-15 acres',
      terrain: 'Wooded hills, farmland, lakes, stone walls',
      soilType: 'Glacial till, stony loam',
      floodRisk: 'Low (check stream/pond adjacency)',
    },
    taxInfo: {
      propertyTaxRate: '1.62%',
      homesteadExemption: 'Residential exemption varies by town',
    },
    schoolDistrict: 'Tantasqua Regional (Sturbridge), Wachusett Regional (good)',
    nearestHospital: 'UMass Memorial Medical (Worcester, 25 min) — neurology; Mass General (Boston, 80 min) — top MG center',
    nearestGrocery: 'Big Y, Hannaford, Price Chopper (10-15 min)',
    population: '~10,000 (Sturbridge)',
    pros: ['Mass General access 80 min', 'UMass neurology 25 min', 'BOS airport 75 min', '"A place like Mass is nice"', 'NJ friends 3 hrs', 'Rural but not remote', 'I-90/Mass Pike access'],
    cons: ['5% MA income tax', 'Higher property tax', 'Cold winters', 'MA permitting is stricter', 'Higher overall cost of living'],
    notes: 'You said "a place like Mass is nice" — this is it. Central MA gives you rural New England living at a fraction of Eastern MA costs. UMass Memorial in Worcester has neurology (25 min), and Mass General is 80 min for top-tier MG care. BOS Logan is ~75 min via Mass Pike. NJ friends can drive in 3 hours. MA has 5% flat income tax and stricter building codes than other states on this list — you need a licensed contractor for most work. But MA schools are consistently ranked #1 nationally. Sturbridge (Old Sturbridge Village) has great New England character. The trade-off for the culture and healthcare access is higher cost of living and less building freedom.',
    rating: 3,
    createdAt: new Date().toISOString(),
  },
]

export const defaultChatHistory = []

// Pre-populated scorecard scores for all seed areas
// Scores are 1-10 based on criteria.js guides
const _s = (score) => ({ score, notes: '' })

export const defaultScorecard = {
  weights: getDefaultWeights(),
  scores: {
    // 0: Clark County, WA — Battle Ground / Ridgefield
    [_areaIds[0]]: {
      financial:       { propertyTax: _s(8), incomeTax: _s(10), salesTax: _s(3), landCost: _s(4), costOfLiving: _s(6), insurance: _s(7) },
      buildingFreedom: { permitProcess: _s(6), ownerBuilder: _s(7), codeStrictness: _s(6), hoaFreedom: _s(8), zoningFlexibility: _s(7) },
      healthcare:      { mgDistance: _s(8), mgQuality: _s(9), emergencyCare: _s(8), generalMedical: _s(8), pharmacySpecialist: _s(8) },
      transportation:  { airportDistance: _s(8), airportQuality: _s(8), roadAccess: _s(7), cityProximity: _s(8) },
      climate:         { summerComfort: _s(8), winterComfort: _s(6), disasterRisk: _s(7), sunshine: _s(5), humidity: _s(6) },
      schools:         { districtRating: _s(8), schoolChoice: _s(7), extracurriculars: _s(7), higherEd: _s(7) },
      infrastructure:  { internet: _s(7), cellCoverage: _s(8), waterReliability: _s(7), electricReliability: _s(8) },
      community:       { culturalAmenities: _s(7), outdoorRec: _s(8), communityFeel: _s(7), friendsFamily: _s(4) },
      safety:          { crimeRate: _s(7), naturalHazards: _s(7), emergencyServices: _s(7), regulatoryStability: _s(7) },
      landQuality:     { terrainViews: _s(8), soilQuality: _s(7), waterAccess: _s(7), privacy: _s(7) },
    },
    // 1: Thurston County, WA — Olympia / Yelm / Tenino
    [_areaIds[1]]: {
      financial:       { propertyTax: _s(7), incomeTax: _s(10), salesTax: _s(3), landCost: _s(6), costOfLiving: _s(6), insurance: _s(7) },
      buildingFreedom: { permitProcess: _s(6), ownerBuilder: _s(7), codeStrictness: _s(6), hoaFreedom: _s(8), zoningFlexibility: _s(7) },
      healthcare:      { mgDistance: _s(5), mgQuality: _s(8), emergencyCare: _s(7), generalMedical: _s(7), pharmacySpecialist: _s(7) },
      transportation:  { airportDistance: _s(5), airportQuality: _s(7), roadAccess: _s(7), cityProximity: _s(5) },
      climate:         { summerComfort: _s(8), winterComfort: _s(6), disasterRisk: _s(7), sunshine: _s(4), humidity: _s(5) },
      schools:         { districtRating: _s(6), schoolChoice: _s(6), extracurriculars: _s(6), higherEd: _s(6) },
      infrastructure:  { internet: _s(5), cellCoverage: _s(6), waterReliability: _s(7), electricReliability: _s(7) },
      community:       { culturalAmenities: _s(5), outdoorRec: _s(7), communityFeel: _s(7), friendsFamily: _s(3) },
      safety:          { crimeRate: _s(6), naturalHazards: _s(6), emergencyServices: _s(7), regulatoryStability: _s(7) },
      landQuality:     { terrainViews: _s(6), soilQuality: _s(6), waterAccess: _s(7), privacy: _s(8) },
    },
    // 2: Cowlitz County, WA — Woodland / Castle Rock
    [_areaIds[2]]: {
      financial:       { propertyTax: _s(7), incomeTax: _s(10), salesTax: _s(3), landCost: _s(8), costOfLiving: _s(7), insurance: _s(7) },
      buildingFreedom: { permitProcess: _s(7), ownerBuilder: _s(8), codeStrictness: _s(7), hoaFreedom: _s(9), zoningFlexibility: _s(8) },
      healthcare:      { mgDistance: _s(6), mgQuality: _s(9), emergencyCare: _s(6), generalMedical: _s(6), pharmacySpecialist: _s(6) },
      transportation:  { airportDistance: _s(7), airportQuality: _s(8), roadAccess: _s(6), cityProximity: _s(6) },
      climate:         { summerComfort: _s(8), winterComfort: _s(6), disasterRisk: _s(6), sunshine: _s(4), humidity: _s(5) },
      schools:         { districtRating: _s(5), schoolChoice: _s(4), extracurriculars: _s(4), higherEd: _s(4) },
      infrastructure:  { internet: _s(4), cellCoverage: _s(5), waterReliability: _s(7), electricReliability: _s(9) },
      community:       { culturalAmenities: _s(3), outdoorRec: _s(7), communityFeel: _s(6), friendsFamily: _s(3) },
      safety:          { crimeRate: _s(5), naturalHazards: _s(5), emergencyServices: _s(5), regulatoryStability: _s(7) },
      landQuality:     { terrainViews: _s(7), soilQuality: _s(7), waterAccess: _s(8), privacy: _s(9) },
    },
    // 3: Yavapai County, AZ — Prescott Valley / Chino Valley
    [_areaIds[3]]: {
      financial:       { propertyTax: _s(9), incomeTax: _s(8), salesTax: _s(5), landCost: _s(8), costOfLiving: _s(7), insurance: _s(7) },
      buildingFreedom: { permitProcess: _s(8), ownerBuilder: _s(10), codeStrictness: _s(8), hoaFreedom: _s(9), zoningFlexibility: _s(8) },
      healthcare:      { mgDistance: _s(4), mgQuality: _s(8), emergencyCare: _s(7), generalMedical: _s(7), pharmacySpecialist: _s(7) },
      transportation:  { airportDistance: _s(4), airportQuality: _s(8), roadAccess: _s(7), cityProximity: _s(5) },
      climate:         { summerComfort: _s(6), winterComfort: _s(6), disasterRisk: _s(6), sunshine: _s(9), humidity: _s(9) },
      schools:         { districtRating: _s(6), schoolChoice: _s(5), extracurriculars: _s(5), higherEd: _s(5) },
      infrastructure:  { internet: _s(6), cellCoverage: _s(7), waterReliability: _s(5), electricReliability: _s(7) },
      community:       { culturalAmenities: _s(5), outdoorRec: _s(8), communityFeel: _s(7), friendsFamily: _s(3) },
      safety:          { crimeRate: _s(7), naturalHazards: _s(5), emergencyServices: _s(6), regulatoryStability: _s(7) },
      landQuality:     { terrainViews: _s(8), soilQuality: _s(4), waterAccess: _s(3), privacy: _s(8) },
    },
    // 4: Pima County, AZ — Vail / Marana
    [_areaIds[4]]: {
      financial:       { propertyTax: _s(9), incomeTax: _s(8), salesTax: _s(5), landCost: _s(9), costOfLiving: _s(8), insurance: _s(8) },
      buildingFreedom: { permitProcess: _s(8), ownerBuilder: _s(10), codeStrictness: _s(8), hoaFreedom: _s(9), zoningFlexibility: _s(8) },
      healthcare:      { mgDistance: _s(7), mgQuality: _s(7), emergencyCare: _s(7), generalMedical: _s(7), pharmacySpecialist: _s(7) },
      transportation:  { airportDistance: _s(5), airportQuality: _s(5), roadAccess: _s(7), cityProximity: _s(7) },
      climate:         { summerComfort: _s(3), winterComfort: _s(8), disasterRisk: _s(7), sunshine: _s(10), humidity: _s(9) },
      schools:         { districtRating: _s(9), schoolChoice: _s(7), extracurriculars: _s(7), higherEd: _s(8) },
      infrastructure:  { internet: _s(6), cellCoverage: _s(7), waterReliability: _s(5), electricReliability: _s(7) },
      community:       { culturalAmenities: _s(6), outdoorRec: _s(7), communityFeel: _s(6), friendsFamily: _s(3) },
      safety:          { crimeRate: _s(6), naturalHazards: _s(6), emergencyServices: _s(6), regulatoryStability: _s(7) },
      landQuality:     { terrainViews: _s(7), soilQuality: _s(4), waterAccess: _s(3), privacy: _s(8) },
    },
    // 5: Pinal County, AZ — Casa Grande / Florence
    [_areaIds[5]]: {
      financial:       { propertyTax: _s(9), incomeTax: _s(8), salesTax: _s(5), landCost: _s(10), costOfLiving: _s(9), insurance: _s(8) },
      buildingFreedom: { permitProcess: _s(9), ownerBuilder: _s(10), codeStrictness: _s(9), hoaFreedom: _s(9), zoningFlexibility: _s(9) },
      healthcare:      { mgDistance: _s(6), mgQuality: _s(8), emergencyCare: _s(6), generalMedical: _s(6), pharmacySpecialist: _s(6) },
      transportation:  { airportDistance: _s(7), airportQuality: _s(8), roadAccess: _s(7), cityProximity: _s(6) },
      climate:         { summerComfort: _s(2), winterComfort: _s(8), disasterRisk: _s(7), sunshine: _s(10), humidity: _s(9) },
      schools:         { districtRating: _s(4), schoolChoice: _s(4), extracurriculars: _s(4), higherEd: _s(3) },
      infrastructure:  { internet: _s(4), cellCoverage: _s(6), waterReliability: _s(4), electricReliability: _s(7) },
      community:       { culturalAmenities: _s(3), outdoorRec: _s(5), communityFeel: _s(4), friendsFamily: _s(3) },
      safety:          { crimeRate: _s(5), naturalHazards: _s(6), emergencyServices: _s(5), regulatoryStability: _s(7) },
      landQuality:     { terrainViews: _s(3), soilQuality: _s(4), waterAccess: _s(2), privacy: _s(9) },
    },
    // 6: Hays County, TX — Dripping Springs / Wimberley
    [_areaIds[6]]: {
      financial:       { propertyTax: _s(4), incomeTax: _s(10), salesTax: _s(4), landCost: _s(4), costOfLiving: _s(5), insurance: _s(6) },
      buildingFreedom: { permitProcess: _s(6), ownerBuilder: _s(7), codeStrictness: _s(6), hoaFreedom: _s(6), zoningFlexibility: _s(6) },
      healthcare:      { mgDistance: _s(7), mgQuality: _s(7), emergencyCare: _s(7), generalMedical: _s(7), pharmacySpecialist: _s(7) },
      transportation:  { airportDistance: _s(7), airportQuality: _s(7), roadAccess: _s(7), cityProximity: _s(8) },
      climate:         { summerComfort: _s(4), winterComfort: _s(7), disasterRisk: _s(5), sunshine: _s(7), humidity: _s(5) },
      schools:         { districtRating: _s(9), schoolChoice: _s(8), extracurriculars: _s(8), higherEd: _s(8) },
      infrastructure:  { internet: _s(8), cellCoverage: _s(8), waterReliability: _s(6), electricReliability: _s(7) },
      community:       { culturalAmenities: _s(7), outdoorRec: _s(7), communityFeel: _s(8), friendsFamily: _s(4) },
      safety:          { crimeRate: _s(8), naturalHazards: _s(5), emergencyServices: _s(7), regulatoryStability: _s(7) },
      landQuality:     { terrainViews: _s(8), soilQuality: _s(5), waterAccess: _s(5), privacy: _s(7) },
    },
    // 7: Comal County, TX — Canyon Lake / New Braunfels
    [_areaIds[7]]: {
      financial:       { propertyTax: _s(4), incomeTax: _s(10), salesTax: _s(4), landCost: _s(5), costOfLiving: _s(6), insurance: _s(6) },
      buildingFreedom: { permitProcess: _s(7), ownerBuilder: _s(7), codeStrictness: _s(7), hoaFreedom: _s(7), zoningFlexibility: _s(7) },
      healthcare:      { mgDistance: _s(7), mgQuality: _s(7), emergencyCare: _s(7), generalMedical: _s(7), pharmacySpecialist: _s(7) },
      transportation:  { airportDistance: _s(7), airportQuality: _s(6), roadAccess: _s(7), cityProximity: _s(8) },
      climate:         { summerComfort: _s(5), winterComfort: _s(7), disasterRisk: _s(5), sunshine: _s(7), humidity: _s(5) },
      schools:         { districtRating: _s(8), schoolChoice: _s(7), extracurriculars: _s(7), higherEd: _s(7) },
      infrastructure:  { internet: _s(7), cellCoverage: _s(8), waterReliability: _s(6), electricReliability: _s(7) },
      community:       { culturalAmenities: _s(7), outdoorRec: _s(8), communityFeel: _s(8), friendsFamily: _s(4) },
      safety:          { crimeRate: _s(7), naturalHazards: _s(5), emergencyServices: _s(7), regulatoryStability: _s(7) },
      landQuality:     { terrainViews: _s(8), soilQuality: _s(5), waterAccess: _s(6), privacy: _s(7) },
    },
    // 8: Bastrop County, TX — Bastrop / Smithville
    [_areaIds[8]]: {
      financial:       { propertyTax: _s(4), incomeTax: _s(10), salesTax: _s(4), landCost: _s(7), costOfLiving: _s(7), insurance: _s(5) },
      buildingFreedom: { permitProcess: _s(8), ownerBuilder: _s(8), codeStrictness: _s(8), hoaFreedom: _s(9), zoningFlexibility: _s(8) },
      healthcare:      { mgDistance: _s(7), mgQuality: _s(7), emergencyCare: _s(6), generalMedical: _s(6), pharmacySpecialist: _s(6) },
      transportation:  { airportDistance: _s(7), airportQuality: _s(7), roadAccess: _s(6), cityProximity: _s(7) },
      climate:         { summerComfort: _s(4), winterComfort: _s(7), disasterRisk: _s(5), sunshine: _s(7), humidity: _s(5) },
      schools:         { districtRating: _s(5), schoolChoice: _s(5), extracurriculars: _s(5), higherEd: _s(6) },
      infrastructure:  { internet: _s(5), cellCoverage: _s(6), waterReliability: _s(6), electricReliability: _s(7) },
      community:       { culturalAmenities: _s(5), outdoorRec: _s(7), communityFeel: _s(7), friendsFamily: _s(3) },
      safety:          { crimeRate: _s(6), naturalHazards: _s(4), emergencyServices: _s(6), regulatoryStability: _s(7) },
      landQuality:     { terrainViews: _s(7), soilQuality: _s(7), waterAccess: _s(6), privacy: _s(8) },
    },
    // 9: El Paso County, CO — Colorado Springs / Falcon / Peyton
    [_areaIds[9]]: {
      financial:       { propertyTax: _s(10), incomeTax: _s(6), salesTax: _s(5), landCost: _s(7), costOfLiving: _s(6), insurance: _s(7) },
      buildingFreedom: { permitProcess: _s(6), ownerBuilder: _s(7), codeStrictness: _s(6), hoaFreedom: _s(7), zoningFlexibility: _s(7) },
      healthcare:      { mgDistance: _s(5), mgQuality: _s(8), emergencyCare: _s(8), generalMedical: _s(8), pharmacySpecialist: _s(8) },
      transportation:  { airportDistance: _s(5), airportQuality: _s(9), roadAccess: _s(8), cityProximity: _s(7) },
      climate:         { summerComfort: _s(8), winterComfort: _s(4), disasterRisk: _s(5), sunshine: _s(10), humidity: _s(9) },
      schools:         { districtRating: _s(8), schoolChoice: _s(7), extracurriculars: _s(8), higherEd: _s(7) },
      infrastructure:  { internet: _s(7), cellCoverage: _s(8), waterReliability: _s(5), electricReliability: _s(7) },
      community:       { culturalAmenities: _s(7), outdoorRec: _s(10), communityFeel: _s(7), friendsFamily: _s(3) },
      safety:          { crimeRate: _s(6), naturalHazards: _s(5), emergencyServices: _s(8), regulatoryStability: _s(7) },
      landQuality:     { terrainViews: _s(9), soilQuality: _s(5), waterAccess: _s(4), privacy: _s(7) },
    },
    // 10: Porter County, IN — Valparaiso / Chesterton
    [_areaIds[10]]: {
      financial:       { propertyTax: _s(8), incomeTax: _s(8), salesTax: _s(6), landCost: _s(8), costOfLiving: _s(8), insurance: _s(7) },
      buildingFreedom: { permitProcess: _s(7), ownerBuilder: _s(7), codeStrictness: _s(7), hoaFreedom: _s(8), zoningFlexibility: _s(7) },
      healthcare:      { mgDistance: _s(5), mgQuality: _s(9), emergencyCare: _s(7), generalMedical: _s(7), pharmacySpecialist: _s(7) },
      transportation:  { airportDistance: _s(6), airportQuality: _s(10), roadAccess: _s(7), cityProximity: _s(7) },
      climate:         { summerComfort: _s(7), winterComfort: _s(3), disasterRisk: _s(5), sunshine: _s(5), humidity: _s(5) },
      schools:         { districtRating: _s(8), schoolChoice: _s(7), extracurriculars: _s(7), higherEd: _s(7) },
      infrastructure:  { internet: _s(7), cellCoverage: _s(8), waterReliability: _s(8), electricReliability: _s(7) },
      community:       { culturalAmenities: _s(6), outdoorRec: _s(7), communityFeel: _s(7), friendsFamily: _s(5) },
      safety:          { crimeRate: _s(7), naturalHazards: _s(6), emergencyServices: _s(7), regulatoryStability: _s(7) },
      landQuality:     { terrainViews: _s(3), soilQuality: _s(9), waterAccess: _s(8), privacy: _s(7) },
    },
    // 11: Hillsborough County, NH — Milford / Amherst / Hollis
    [_areaIds[11]]: {
      financial:       { propertyTax: _s(3), incomeTax: _s(10), salesTax: _s(10), landCost: _s(5), costOfLiving: _s(5), insurance: _s(7) },
      buildingFreedom: { permitProcess: _s(6), ownerBuilder: _s(7), codeStrictness: _s(6), hoaFreedom: _s(8), zoningFlexibility: _s(6) },
      healthcare:      { mgDistance: _s(6), mgQuality: _s(10), emergencyCare: _s(7), generalMedical: _s(7), pharmacySpecialist: _s(8) },
      transportation:  { airportDistance: _s(7), airportQuality: _s(9), roadAccess: _s(8), cityProximity: _s(7) },
      climate:         { summerComfort: _s(8), winterComfort: _s(3), disasterRisk: _s(7), sunshine: _s(6), humidity: _s(6) },
      schools:         { districtRating: _s(9), schoolChoice: _s(8), extracurriculars: _s(8), higherEd: _s(7) },
      infrastructure:  { internet: _s(7), cellCoverage: _s(8), waterReliability: _s(7), electricReliability: _s(7) },
      community:       { culturalAmenities: _s(7), outdoorRec: _s(8), communityFeel: _s(9), friendsFamily: _s(7) },
      safety:          { crimeRate: _s(9), naturalHazards: _s(7), emergencyServices: _s(7), regulatoryStability: _s(8) },
      landQuality:     { terrainViews: _s(8), soilQuality: _s(5), waterAccess: _s(7), privacy: _s(8) },
    },
    // 12: Worcester County, MA — Sturbridge / Brookfield / Spencer
    [_areaIds[12]]: {
      financial:       { propertyTax: _s(4), incomeTax: _s(6), salesTax: _s(5), landCost: _s(6), costOfLiving: _s(5), insurance: _s(7) },
      buildingFreedom: { permitProcess: _s(4), ownerBuilder: _s(4), codeStrictness: _s(4), hoaFreedom: _s(7), zoningFlexibility: _s(5) },
      healthcare:      { mgDistance: _s(6), mgQuality: _s(10), emergencyCare: _s(7), generalMedical: _s(7), pharmacySpecialist: _s(8) },
      transportation:  { airportDistance: _s(5), airportQuality: _s(9), roadAccess: _s(8), cityProximity: _s(6) },
      climate:         { summerComfort: _s(8), winterComfort: _s(3), disasterRisk: _s(7), sunshine: _s(6), humidity: _s(6) },
      schools:         { districtRating: _s(8), schoolChoice: _s(7), extracurriculars: _s(7), higherEd: _s(8) },
      infrastructure:  { internet: _s(6), cellCoverage: _s(7), waterReliability: _s(7), electricReliability: _s(7) },
      community:       { culturalAmenities: _s(7), outdoorRec: _s(7), communityFeel: _s(8), friendsFamily: _s(7) },
      safety:          { crimeRate: _s(8), naturalHazards: _s(7), emergencyServices: _s(7), regulatoryStability: _s(7) },
      landQuality:     { terrainViews: _s(7), soilQuality: _s(5), waterAccess: _s(7), privacy: _s(7) },
    },
  },
}

export const defaultState = {
  settings: defaultSettings,
  finances: defaultFinances,
  requirements: defaultRequirements,
  timeline: defaultTimeline,
  locations: defaultAreas,
  properties: [],
  scorecard: defaultScorecard,
  chatHistory: defaultChatHistory,
}
